## Clean Incosistent Data From Rightmove

In [9]:
import pandas as pd

df_rm_cardiff = pd.read_csv("RAW_DATA/rightmove/properties_with_bedrooms_auto_cardiff.csv")

In [10]:
df_rm_cardiff["price"] = df_rm_cardiff["price"].str.replace(r"\D", "", regex=True)
# df_rm_cardiff["area"] = df_rm_cardiff["area"].str.replace(r"\D", "", regex=True)
df_rm_cardiff["area"] = df_rm_cardiff["area"].str.extract(r"(\d+)").astype(float)

In [11]:
df_rm_cardiff

,title,location,price,property_type,bedrooms,bathrooms,area,link
0,"Rudry Road, Lisvane, CF14","Rudry Road, Lisvane, CF14",8000000,Detached,7,11,NaN,https://www.rightmove.co.uk/properties/8766502...
1,"Hollybush Road, Cardiff, CF23","Hollybush Road, Cardiff, CF23",3500000,Detached,6,5,NaN,https://www.rightmove.co.uk/properties/8766444...
2,"St. Brides-Super-Ely, Cardiff, CF5","St. Brides-Super-Ely, Cardiff, CF5",3000000,Detached,9,8,NaN,https://www.rightmove.co.uk/properties/8766503...
3,"Llandennis Avenue, Cardiff, CF23","Llandennis Avenue, Cardiff, CF23",2700000,Detached,6,9,NaN,https://www.rightmove.co.uk/properties/1735212...
4,"Hollybush Road, Cardiff, CF23","Hollybush Road, Cardiff, CF23",2500000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1660201...
5,"Heol Y Parc, Pentyrch, Cardiff, CF15","Heol Y Parc, Pentyrch, Cardiff, CF15",2500000,Detached,5,6,638.0,https://www.rightmove.co.uk/properties/1535486...
6,"Penhill House, Llandaff Road, Cardiff, CF11 9PX","Penhill House, Llandaff Road, Cardiff, CF11 9PX",2250000,Detached,7,5,NaN,https://www.rightmove.co.uk/properties/1716868...
7,"Maples, Lisvane Road, Lisvane, Cardiff","Maples, Lisvane Road, Lisvane, Cardiff",2000000,Detached,5,4,416.0,https://www.rightmove.co.uk/properties/1735466...
8,"Palace Road, Llandaff, Cardiff","Palace Road, Llandaff, Cardiff",1750000,Semi-Detached,7,3,370.0,https://www.rightmove.co.uk/properties/1652900...
9,"Heol Hir, Cardiff, CF14","Heol Hir, Cardiff, CF14",1750000,Country House,6,5,NaN,https://www.rightmove.co.uk/properties/1653543...
10,"Mill Road, Lisvane, Cardiff","Mill Road, Lisvane, Cardiff",1550000,Detached,6,3,299.0,https://www.rightmove.co.uk/properties/1736714...
11,"17 Cefn-Coed Road, Cyncoed, Cardiff, CF23 6AN,...","17 Cefn-Coed Road, Cyncoed, Cardiff, CF23 6AN,...",1500000,Detached,9,5,381.0,https://www.rightmove.co.uk/properties/1729392...
12,"Lake Road East, Cardiff, CF23","Lake Road East, Cardiff, CF23",1500000,Detached,5,1,NaN,https://www.rightmove.co.uk/properties/8769343...
13,"Mill Road, Lisvane, Cardiff","Mill Road, Lisvane, Cardiff",1500000,Detached,5,3,295.0,https://www.rightmove.co.uk/properties/1728070...
14,"Llangorse Road, Cyncoed, Cardiff, CF23","Llangorse Road, Cyncoed, Cardiff, CF23",1500000,Detached,4,3,NaN,https://www.rightmove.co.uk/properties/1732243...
15,"Cefn Coed Crescent, Cyncoed, Cardiff, CF23","Cefn Coed Crescent, Cyncoed, Cardiff, CF23",1450000,Detached,5,5,NaN,https://www.rightmove.co.uk/properties/1731131...
16,Morganstown,Morganstown,1400000,Detached,4,2,174.0,https://www.rightmove.co.uk/properties/1657164...
17,"Cyncoed Road, Cyncoed, Cardiff, CF23","Cyncoed Road, Cyncoed, Cardiff, CF23",1400000,Detached,6,2,NaN,https://www.rightmove.co.uk/properties/1736485...
18,"Druidstone Road, Old St Mellons, Cardiff, CF3","Druidstone Road, Old St Mellons, Cardiff, CF3",1395000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1698522...
19,"Church Road, Old St. Mellons","Church Road, Old St. Mellons",1395000,Detached,5,5,NaN,https://www.rightmove.co.uk/properties/1712395...
20,"Ty'r Winch Road, Old St. Mellons","Ty'r Winch Road, Old St. Mellons",1350000,Detached,6,4,NaN,https://www.rightmove.co.uk/properties/1733405...
21,"Portland Place, Lisvane, Cardiff. CF14","Portland Place, Lisvane, Cardiff. CF14",1300000,Detached,6,10,337.0,https://www.rightmove.co.uk/properties/1690635...
22,"Llandennis Avenue, Cyncoed, Cardiff, CF23","Llandennis Avenue, Cyncoed, Cardiff, CF23",1300000,Detached,4,2,NaN,https://www.rightmove.co.uk/properties/1671692...
23,"The Mount, Lisvane, Cardiff","The Mount, Lisvane, Cardiff",1295000,Detached,5,3,NaN,https://www.rightmove.co.uk/properties/1617843...

In [12]:
import os 
os.makedirs("CLEANED_DATA/rightmove", exist_ok=True)

# df_rm_london.to_csv("CLEANED_DATA/rightmove/rm_properties_london.csv", index=False)

In [13]:
def clean_rightmove_data(file_path, output_path):
    df = pd.read_csv(file_path)
    df["price"] = df["price"].str.replace(r"\D", "", regex=True)
    # df["area"] = df["area"].str.replace(r"\D", "", regex=True)
    df["area"] = df["area"].str.extract(r"(\d+)").astype(float)
    df.to_csv(output_path, index=False)


clean_rightmove_data("RAW_DATA/rightmove/properties_with_bedrooms_auto_london.csv", "CLEANED_DATA/rightmove/rm_properties_london.csv")

In [14]:
list_cities = ["Leicester", "Birmingham", "London", "Glasgow", "Edinburgh", "Newcastle", "Bristol", "Manchester", "Notingham", "Sheffield", "Liverpool", "Cardiff", "Belfast", "Leeds", "Southampton"]

for city in list_cities:
    print(f"Cleaning data for {city}...")
    clean_rightmove_data(f"RAW_DATA/rightmove/properties_with_bedrooms_auto_{city.lower()}.csv", f"CLEANED_DATA/rightmove/rm_properties_{city.lower()}.csv")

Cleaning data for Leicester...
Cleaning data for Birmingham...
Cleaning data for London...
Cleaning data for Glasgow...
Cleaning data for Edinburgh...
Cleaning data for Newcastle...
Cleaning data for Bristol...
Cleaning data for Manchester...
Cleaning data for Notingham...
Cleaning data for Sheffield...
Cleaning data for Liverpool...
Cleaning data for Cardiff...
Cleaning data for Belfast...
Cleaning data for Leeds...
Cleaning data for Southampton...

## Clean Incosistent Data From Zoopla

In [64]:
import pandas as pd

df_rm_london = pd.read_csv("RAW_DATA/zoopla/zoopla_properties_London.csv")

In [65]:
df_rm_london

,title,location,price,property_type,bedrooms,bathrooms,area,link
0,"New Kings Road, Parsons Green, London SW6","New Kings Road, Parsons Green, London SW6","£295,000",Leasehold,1 bed,1 bath,323 sq ft,https://www.zoopla.co.uk/for-sale/details/6970...
1,"St. Luke's Avenue, London SW4","St. Luke's Avenue, London SW4","£530,000",Chain free,2 beds,1 bath,549 sq ft,https://www.zoopla.co.uk/for-sale/details/7274...
2,"Powis Square, Notting Hill, London W11","Powis Square, Notting Hill, London W11","£1,250,000",Leasehold,2 beds,2 baths,898 sq ft,https://www.zoopla.co.uk/for-sale/details/7207...
3,"Woodmansterne Lane, Wallington SM6","Woodmansterne Lane, Wallington SM6","£750,000",Freehold,4 beds,2 baths,1359 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
4,"700 High Road, London N17","700 High Road, London N17","£100,000",Shared Ownership,1 bed,1 bath,NaN,https://www.zoopla.co.uk/new-homes/details/727...
5,"Wellesley Road, Croydon CR0","Wellesley Road, Croydon CR0","£83,125",Shared Ownership,1 bed,1 bath,539 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
6,"Old Kent Road, London SE15","Old Kent Road, London SE15","£792,000",Leasehold,2 beds,2 baths,915 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
7,"Old Kent Road, London SE15","Old Kent Road, London SE15","£690,000",Leasehold,2 beds,2 baths,785 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
8,"Old Kent Road, London SE15","Old Kent Road, London SE15","£667,000",Leasehold,2 beds,1 bath,808 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
9,"Chelsea Botanica, Watermeadow Lane SW6","Chelsea Botanica, Watermeadow Lane SW6","£143,750",Shared Ownership,1 bed,NaN,NaN,https://www.zoopla.co.uk/new-homes/details/727...
10,"Chelsea Botanica, Watermeadow Lane SW6","Chelsea Botanica, Watermeadow Lane SW6","£575,000",Shared Ownership,1 bed,NaN,NaN,https://www.zoopla.co.uk/new-homes/details/727...
11,"Abbey Road, Barking IG11","Abbey Road, Barking IG11","£300,000",Shared Ownership,1 bed,1 bath,NaN,https://www.zoopla.co.uk/new-homes/details/727...
12,"Station Road, Croydon CR0","Station Road, Croydon CR0","£390,000",Low mortgage,2 beds,2 baths,751 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
13,"Station Road, Croydon CR0","Station Road, Croydon CR0","£400,000",Low mortgage,2 beds,2 baths,751 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
14,"Kent Avenue, Dagenham RM9","Kent Avenue, Dagenham RM9","£307,000",Leasehold,1 bed,1 bath,NaN,https://www.zoopla.co.uk/new-homes/details/719...
15,"Old Kent Road, London SE15","Old Kent Road, London SE15","£551,000",Leasehold,1 bed,1 bath,538 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
16,"Old Kent Road, London SE15","Old Kent Road, London SE15","£495,000",Leasehold,1 bed,1 bath,NaN,https://www.zoopla.co.uk/new-homes/details/727...
17,"Capital Interchange Way, Brentford TW8","Capital Interchange Way, Brentford TW8","£520,000",Leasehold,1 bed,1 bath,NaN,https://www.zoopla.co.uk/new-homes/details/727...
18,"Capital Interchange Way, Brentford TW8","Capital Interchange Way, Brentford TW8","£599,000",Leasehold,2 beds,2 baths,NaN,https://www.zoopla.co.uk/new-homes/details/727...
19,"Banks Road, Kidbrooke SE3","Banks Road, Kidbrooke SE3","£116,875",Shared Ownership,2 beds,1 bath,767 sq ft,https://www.zoopla.co.uk/new-homes/details/727...
20,"Middle Road, Hanwell W7","Middle Road, Hanwell W7","£607,500",Leasehold,2 beds,2 baths,NaN,https://www.zoopla.co.uk/new-homes/details/727...

In [77]:
import os 
os.makedirs("CLEANED_DATA/zoopla", exist_ok=True)

def clean_rightmove_data(file_path, output_path):
    df = pd.read_csv(file_path)
    df["price"] = df["price"].str.replace(r"\D", "", regex=True)
    df["bedrooms"] = df["bedrooms"].str.replace(r"\D", "", regex=True)
    df["bathrooms"] = df["bathrooms"].str.replace(r"\D", "", regex=True)
    df["area"] = df["area"].astype(str).str.replace(r"\D", "", regex=True)
    # print("Area cleaned")

    df.to_csv(output_path, index=False)


clean_rightmove_data("RAW_DATA/zoopla/zoopla_properties_London.csv", "CLEANED_DATA/zoopla/zoopla_properties_london.csv")

In [78]:
list_cities = ["Leicester", "Birmingham", "London", "Glasgow", "Edinburgh", "Newcastle", "Bristol", "Manchester", "Notingham", "Sheffield", "Liverpool", "Cardiff", "Belfast", "Leeds", "Southampton"]

for city in list_cities:
    try:
        print(f"Cleaning data for {city}...")
        clean_rightmove_data(f"RAW_DATA/zoopla/zoopla_properties_{city}.csv", f"CLEANED_DATA/zoopla/zoopla_properties_{city.lower()}.csv")
    except Exception as e:
        print(f"Error cleaning data for {city}: {e}")

Cleaning data for Leicester...
Cleaning data for Birmingham...
Cleaning data for London...
Cleaning data for Glasgow...
Cleaning data for Edinburgh...
Cleaning data for Newcastle...
Cleaning data for Bristol...
Cleaning data for Manchester...
Cleaning data for Notingham...
Cleaning data for Sheffield...
Cleaning data for Liverpool...
Cleaning data for Cardiff...
Cleaning data for Belfast...
Error cleaning data for Belfast: No columns to parse from file
Cleaning data for Leeds...
Cleaning data for Southampton...