Regression 
Y =  Price
X =  Features (Area, Bedrooms, Bathroom, Location,... etc)

In [5]:
from sklearn.linear_model import LinearRegression

In [ ]:
import pandas as pd

list_cities = ["Leicester", "Birmingham", "London", "Glasgow", "Edinburgh", "Newcastle", "Bristol", "Manchester", "Nottingham", "Sheffield", "Liverpool", "Cardiff", "Belfast", "Leeds", "Southampton"]

df_list = []

for city in list_cities:
    df_temp = pd.read_csv(f"CLEANED_DATA/rightmove/rm_properties_{city.lower()}.csv")
    df_temp["city"] = city
    df_list.append(df_temp)

df_all_cities_original = pd.concat(df_list, ignore_index=True)

df_all_cities = df_all_cities_original.copy()
df_all_cities

In [2]:
df_all_cities["area"]  = df_all_cities["area"].fillna(df_all_cities["area"].median(), inplace=True)

/var/folders/zb/ckbmp2j1113556mqnd3w6n0w0000gn/T/ipykernel_1583/1064581598.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_all_cities["area"]  = df_all_cities["area"].fillna(df_all_cities["area"].median(), inplace=True)

In [3]:
df_all_cities

,title,location,price,property_type,bedrooms,bathrooms,area,link,city
0,"Stone Penn Lane, Holwell, Melton Mowbray","Stone Penn Lane, Holwell, Melton Mowbray",1750000.0,Equestrian Facility,4.0,2.0,393.0,https://www.rightmove.co.uk/properties/1736345...,Leicester
1,"Hallaton, Hallaton, LE16","Hallaton, Hallaton, LE16",1175000.0,Detached,5.0,2.0,393.0,https://www.rightmove.co.uk/properties/1736637...,Leicester
2,"Wibtoft, Warwickshire","Wibtoft, Warwickshire",950000.0,Detached,5.0,3.0,393.0,https://www.rightmove.co.uk/properties/1736322...,Leicester
3,"Bakehouse Lane, Twyford","Bakehouse Lane, Twyford",850000.0,Detached,4.0,3.0,393.0,https://www.rightmove.co.uk/properties/1736713...,Leicester
4,"Main Street, Fleckney, Leicester","Main Street, Fleckney, Leicester",650000.0,Detached,5.0,2.0,393.0,https://www.rightmove.co.uk/properties/1736208...,Leicester
...,...,...,...,...,...,...,...,...,...
328,"St. Marys Road, Netley Abbey, Hampshire, SO31","St. Marys Road, Netley Abbey, Hampshire, SO31",1100000.0,Semi-Detached,4.0,3.0,393.0,https://www.rightmove.co.uk/properties/1727186...,Southampton
329,"Highfield, Southampton","Highfield, Southampton",995000.0,Detached,4.0,2.0,393.0,https://www.rightmove.co.uk/properties/8719473...,Southampton
330,"Beechmount Road, Bassett, Southampton, Hampshi...","Beechmount Road, Bassett, Southampton, Hampshi...",995000.0,Detached,5.0,4.0,393.0,https://www.rightmove.co.uk/properties/1720234...,Southampton
331,"Pinehurst Road, Southampton","Pinehurst Road, Southampton",995000.0,Detached,5.0,3.0,393.0,https://www.rightmove.co.uk/properties/1730982...,Southampton
332,"High Street, Old Bursledon, Southampton, SO31","High Street, Old Bursledon, Southampton, SO31",995000.0,Detached,3.0,2.0,393.0,https://www.rightmove.co.uk/properties/1717312...,Southampton

In [7]:
X = df_all_cities[["area"]]
X

      area
0    393.0
1    393.0
2    393.0
3    393.0
4    393.0
..     ...
328  393.0
329  393.0
330  393.0
331  393.0
332  393.0

[333 rows x 1 columns]